from __future__ import annotations

from html import escape

from .diagnose import assess
from .latency import latency_spans, total_observed_ms
from .model import Trace
from .pipeline import build_pipeline


def _duration(milliseconds: int) -> str:
    if milliseconds < 1000:
        return f"{milliseconds} ms"
    return f"{milliseconds / 1000:.3f} s"


def render_html(trace: Trace) -> str:
    assessment = assess(trace)
    pipeline = build_pipeline(trace)
    spans = latency_spans(trace)

    pipeline_html = "".join(
        "<li>"
        f"<strong>{escape(stage.label)}</strong> "
        f"<span class=\"state\">{escape(stage.state)}</span> "
        f"{escape(stage.detail)}"
        "</li>"
        for stage in pipeline
    ) or "<li>No pipeline stages confirmed.</li>"

    event_rows = "".join(
        "<tr>"
        f"<td>{escape(event.timestamp.isoformat())}</td>"
        f"<td>{escape(event.source)}</td>"
        f"<td>{escape(event.component)}</td>"
        f"<td>{escape(event.queue_id or '-')}</td>"
        f"<td>{escape(event.kind)}</td>"
        f"<td><code>{escape(event.message)}</code></td>"
        "</tr>"
        for event in trace.events
    ) or '<tr><td colspan="6">No matching events.</td></tr>'

    latency_rows = "".join(
        "<tr>"
        f"<td>{escape(span.from_stage)}</td>"
        f"<td>{escape(span.to_stage)}</td>"
        f"<td>{escape(_duration(span.duration_ms))}</td>"
        "</tr>"
        for span in spans
    ) or '<tr><td colspan="3">Not enough events for latency spans.</td></tr>'

    caveat = (
        f"<p><strong>Caveat:</strong> {escape(assessment.caveat)}</p>"
        if assessment.caveat
        else ""
    )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>mailforensics report</title>
<style>
body {{ font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; max-width: 1180px; margin: 2rem auto; padding: 0 1rem; line-height: 1.45; }}
h1, h2 {{ font-family: system-ui, sans-serif; }}
code {{ white-space: pre-wrap; word-break: break-word; }}
table {{ width: 100%; border-collapse: collapse; margin: 1rem 0 2rem; }}
th, td {{ text-align: left; vertical-align: top; border-bottom: 1px solid #ccc; padding: .5rem; }}
.meta {{ display: grid; grid-template-columns: max-content 1fr; gap: .25rem 1rem; }}
.state {{ font-weight: 700; }}
.small {{ opacity: .75; }}
</style>
</head>
<body>
<h1>mailforensics</h1>
<div class="meta">
<div>Query</div><div>{escape(trace.query)}</div>
<div>Status</div><div>{escape(trace.status)}</div>
<div>Queues</div><div>{escape(", ".join(sorted(trace.queue_ids)) or "-")}</div>
<div>Observed duration</div><div>{escape(_duration(total_observed_ms(trace)))}</div>
</div>

<h2>Assessment</h2>
<p><strong>{escape(assessment.outcome)}</strong> · confidence {escape(assessment.confidence)}</p>
<p>{escape(assessment.summary)}</p>
{caveat}

<h2>Pipeline</h2>
<ol>{pipeline_html}</ol>

<h2>Latency</h2>
<table>
<thead><tr><th>From</th><th>To</th><th>Duration</th></tr></thead>
<tbody>{latency_rows}</tbody>
</table>

<h2>Evidence</h2>
<table>
<thead><tr><th>Timestamp</th><th>Source</th><th>Component</th><th>Queue</th><th>Kind</th><th>Message</th></tr></thead>
<tbody>{event_rows}</tbody>
</table>

<p class="small">Generated by mailforensics. Absence of an event is not proof that a component failed.</p>
</body>
</html>
"""
